### PR TITLE
Use IPv6-enabled NIST pool

### PR DESCRIPTION
**Pull request by stevew817**
Fixing issue #1 
This allows the use of NTP by Thread nodes (i.e. mbed client)

### CODE REVIEW

**Comment by stevew817** [comment]
@bridadan ?

**Comment by bridadan** [comment]
Hi @stevew817, sorry totally missed this PR the first time it went up! As a quick test, I verfied I wasn't able to ping `pool.ntp.org` via IPv6 (it worked with IPv4) from my windows macihne, however I was able to ping `2.pool.ntp.org` via both IPv6 and IPv4. Does this sound correct? I believe this patch is good in that case.

**Comment by stevew817** [comment]
@bridadan that's correct. Pool 2 is dual-stackThis link has more info on IPv6-enabled NTP servers: http://www.internetsociety.org/deploy360/resources/ipv6-time-servers-ntp/

**Comment by bridadan** [comment]
Good enough for me! Have you tested to make sure both IPv4 and IPv6 devices can use this? I'm not near an mbed at the moment.

**Comment by stevew817** [comment]
Yes, my PC (IPv4 only connection) can sync time successfully with pool 2.

**Comment by bridadan** [comment]
Great thanks!

**Pull request merged**
